// Auto-generated pages router
import { Client } from "@libsql/client/web";

import { handleAdminPanelRoute as handleAdminPanelRoute_f6ry6 } from "./api/admin/AdminPanel";
import { handleAITutorHeaderRoute as handleAITutorHeaderRoute_74h2h } from "./api/ai-tutor/AITutorHeader";
import { handleAITutorPageRoute as handleAITutorPageRoute_waa1a } from "./api/ai-tutor/AITutorPage";
import { handleChatMessagesRoute as handleChatMessagesRoute_3id0o } from "./api/ai-tutor/ChatMessages";
import { handleMessageInputRoute as handleMessageInputRoute_5a0li } from "./api/ai-tutor/MessageInput";
import { handleSuggestedPromptsRoute as handleSuggestedPromptsRoute_6srbz } from "./api/ai-tutor/SuggestedPrompts";
import { handleAuthPageRouteRoute as handleAuthPageRouteRoute_kd7du } from "./api/AuthPageRoute";
import { handleCommunitiesFilterRoute as handleCommunitiesFilterRoute_e6t80 } from "./api/communities/CommunitiesFilter";
import { handleCommunitiesGridRoute as handleCommunitiesGridRoute_evxz4 } from "./api/communities/CommunitiesGrid";
import { handleCommunitiesHeaderRoute as handleCommunitiesHeaderRoute_z0gd8 } from "./api/communities/CommunitiesHeader";
import { handleCommunitiesPageRoute as handleCommunitiesPageRoute_lsbt3 } from "./api/communities/CommunitiesPage";
import { handleCreateCommunityModalRoute as handleCreateCommunityModalRoute_tks0c } from "./api/communities/CreateCommunityModal";
import { handleAISuggestionsRoute as handleAISuggestionsRoute_sf8we } from "./api/dashboard/AISuggestions";
import { handleDashboardPageRoute as handleDashboardPageRoute_n2219 } from "./api/dashboard/DashboardPage";
import { handleQuickActionsRoute as handleQuickActionsRoute_16szu } from "./api/dashboard/QuickActions";
import { handleRecentActivityRoute as handleRecentActivityRoute_js47j } from "./api/dashboard/RecentActivity";
import { handleStatsGridRoute as handleStatsGridRoute_sodgb } from "./api/dashboard/StatsGrid";
import { handleUpcomingScheduleRoute as handleUpcomingScheduleRoute_fcra7 } from "./api/dashboard/UpcomingSchedule";
import { handleWelcomeHeaderRoute as handleWelcomeHeaderRoute_7sa60 } from "./api/dashboard/WelcomeHeader";
import { handleFeedPageRoute as handleFeedPageRoute_ej59j } from "./api/FeedPage";
import { handleLandingPageRoute as handleLandingPageRoute_inmd3 } from "./api/LandingPage";
import { handleLeaderboardPageRoute as handleLeaderboardPageRoute_ldh0n } from "./api/leaderboard/LeaderboardPage";
import { handlePodiumRoute as handlePodiumRoute_a1oqj } from "./api/leaderboard/Podium";
import { handleRankListRoute as handleRankListRoute_fyis4 } from "./api/leaderboard/RankList";
import { handleTrophyRoomRoute as handleTrophyRoomRoute_9qmx8 } from "./api/leaderboard/TrophyRoom";
import { handleChatAreaRoute as handleChatAreaRoute_9396g } from "./api/messages/ChatArea";
import { handleMessagesPageRoute as handleMessagesPageRoute_r73b4 } from "./api/messages/MessagesPage";
import { handleMessagesSidebarRoute as handleMessagesSidebarRoute_lxj3a } from "./api/messages/MessagesSidebar";
import { handleNewChatModalRoute as handleNewChatModalRoute_cbjaj } from "./api/messages/NewChatModal";
import { handleCreateFolderModalRoute as handleCreateFolderModalRoute_hko04 } from "./api/notes/CreateFolderModal";
import { handleCreateNoteModalRoute as handleCreateNoteModalRoute_9mx5e } from "./api/notes/CreateNoteModal";
import { handledataRoute as handledataRoute_og8o6 } from "./api/notes/data";
import { handlefileExtractorRoute as handlefileExtractorRoute_jor63 } from "./api/notes/fileExtractor";
import { handleFlashcardsStudyModalRoute as handleFlashcardsStudyModalRoute_chrxq } from "./api/notes/FlashcardsStudyModal";
import { handleFolderBreadcrumbsRoute as handleFolderBreadcrumbsRoute_8sc96 } from "./api/notes/FolderBreadcrumbs";
import { handleFolderGridRoute as handleFolderGridRoute_ks8rb } from "./api/notes/FolderGrid";
import { handleNotesFilterRoute as handleNotesFilterRoute_rd7y0 } from "./api/notes/NotesFilter";
import { handleNotesHeaderRoute as handleNotesHeaderRoute_g3vpg } from "./api/notes/NotesHeader";
import { handleNotesListRoute as handleNotesListRoute_h2cd5 } from "./api/notes/NotesList";
import { handleNotesPageRoute as handleNotesPageRoute_vvmna } from "./api/notes/NotesPage";
import { handletypesRoute as handletypesRoute_mdrc7 } from "./api/notes/types";
import { handleChatPaneRoute as handleChatPaneRoute_s2bsd } from "./api/notes/workspace/ChatPane";
import { handleFlashcardsTabRoute as handleFlashcardsTabRoute_6sw61 } from "./api/notes/workspace/EditorPane/FlashcardsTab";
import { handleindexRoute as handleindexRoute_zyssn } from "./api/notes/workspace/EditorPane/index";
import { handleMermaidViewerRoute as handleMermaidViewerRoute_kn4bp } from "./api/notes/workspace/EditorPane/MermaidViewer";
import { handleSlideCarouselRoute as handleSlideCarouselRoute_qwis2 } from "./api/notes/workspace/EditorPane/SlideCarousel";
import { handleindexRoute as handleindexRoute_vshhh } from "./api/notes/workspace/index";
import { handleNoteWorkspaceModalRoute as handleNoteWorkspaceModalRoute_gqjyl } from "./api/notes/workspace/NoteWorkspaceModal";
import { handleSourcesPaneRoute as handleSourcesPaneRoute_ed19r } from "./api/notes/workspace/SourcesPane";
import { handleStudioPaneRoute as handleStudioPaneRoute_ornb9 } from "./api/notes/workspace/StudioPane";
import { handlestudioUtilsRoute as handlestudioUtilsRoute_kdabb } from "./api/notes/workspace/studioUtils";
import { handleAIInsightsRoute as handleAIInsightsRoute_jmv9l } from "./api/planner/AIInsights";
import { handleAIOptimizerModalRoute as handleAIOptimizerModalRoute_tnd3y } from "./api/planner/AIOptimizerModal";
import { handleCustomDatePickerRoute as handleCustomDatePickerRoute_fn148 } from "./api/planner/CustomDatePicker";
import { handleLongTermGoalsRoute as handleLongTermGoalsRoute_mgy4h } from "./api/planner/LongTermGoals";
import { handlePlannerActionModalRoute as handlePlannerActionModalRoute_jpm7r } from "./api/planner/PlannerActionModal";
import { handlePlannerConfirmModalRoute as handlePlannerConfirmModalRoute_197vi } from "./api/planner/PlannerConfirmModal";
import { handlePlannerHeaderRoute as handlePlannerHeaderRoute_830sj } from "./api/planner/PlannerHeader";
import { handlePlannerPageRoute as handlePlannerPageRoute_22vrw } from "./api/planner/PlannerPage";
import { handleTodayScheduleRoute as handleTodayScheduleRoute_fiaoj } from "./api/planner/TodaySchedule";
import { handleWeeklyGoalsRoute as handleWeeklyGoalsRoute_mnpgw } from "./api/planner/WeeklyGoals";
import { handleProfilePageRoute as handleProfilePageRoute_ksh3j } from "./api/profile/ProfilePage";
import { handleCollaboratorsListRoute as handleCollaboratorsListRoute_7nidb } from "./api/research/CollaboratorsList";
import { handlePaperSearchRoute as handlePaperSearchRoute_itfru } from "./api/research/PaperSearch";
import { handleResearchHeaderRoute as handleResearchHeaderRoute_umo0h } from "./api/research/ResearchHeader";
import { handleResearchPageRoute as handleResearchPageRoute_l31mv } from "./api/research/ResearchPage";
import { handleResearchPapersListRoute as handleResearchPapersListRoute_t96re } from "./api/research/ResearchPapersList";
import { handleResearchStatsRoute as handleResearchStatsRoute_t8j9f } from "./api/research/ResearchStats";
import { handleAccessibilitySettingsPageRoute as handleAccessibilitySettingsPageRoute_g52kg } from "./api/settings/AccessibilitySettingsPage";
import { handleApiKeysPageRoute as handleApiKeysPageRoute_hrllo } from "./api/settings/ApiKeysPage";
import { handleAppearanceSettingsPageRoute as handleAppearanceSettingsPageRoute_n2pk7 } from "./api/settings/AppearanceSettingsPage";
import { handleDataManagementPageRoute as handleDataManagementPageRoute_kn4lw } from "./api/settings/DataManagementPage";
import { handleDataStorageHubPageRoute as handleDataStorageHubPageRoute_gnas9 } from "./api/settings/DataStorageHubPage";
import { handleEmailSettingsPageRoute as handleEmailSettingsPageRoute_a78dj } from "./api/settings/EmailSettingsPage";
import { handleLanguageSettingsPageRoute as handleLanguageSettingsPageRoute_rnok0 } from "./api/settings/LanguageSettingsPage";
import { handleMyCommentsPageRoute as handleMyCommentsPageRoute_y9v5h } from "./api/settings/MyCommentsPage";
import { handleMyLikesPageRoute as handleMyLikesPageRoute_yq1jr } from "./api/settings/MyLikesPage";
import { handleMyPostsPageRoute as handleMyPostsPageRoute_zu33j } from "./api/settings/MyPostsPage";
import { handleMySharesPageRoute as handleMySharesPageRoute_ahwdu } from "./api/settings/MySharesPage";
import { handleNotificationsSettingsPageRoute as handleNotificationsSettingsPageRoute_35xu2 } from "./api/settings/NotificationsSettingsPage";
import { handlePasswordSettingsPageRoute as handlePasswordSettingsPageRoute_1on0p } from "./api/settings/PasswordSettingsPage";
import { handlePreferencesHubPageRoute as handlePreferencesHubPageRoute_5f7xe } from "./api/settings/PreferencesHubPage";
import { handlePrivacySettingsPageRoute as handlePrivacySettingsPageRoute_c1orf } from "./api/settings/PrivacySettingsPage";
import { handleProfileSettingsPageRoute as handleProfileSettingsPageRoute_xr7rf } from "./api/settings/ProfileSettingsPage";
import { handleStorageUsagePageRoute as handleStorageUsagePageRoute_f3c3y } from "./api/settings/StorageUsagePage";
import { handleSettingsPageRoute as handleSettingsPageRoute_waysn } from "./api/SettingsPage";

export const handleAllPagesRoutes = async (url: URL, request: Request, db: Client | null): Promise<Response | null> => {
  let res: Response | null = null;
  
  res = await handleAdminPanelRoute_f6ry6(url, request, db); if (res) return res;
  res = await handleAITutorHeaderRoute_74h2h(url, request, db); if (res) return res;
  res = await handleAITutorPageRoute_waa1a(url, request, db); if (res) return res;
  res = await handleChatMessagesRoute_3id0o(url, request, db); if (res) return res;
  res = await handleMessageInputRoute_5a0li(url, request, db); if (res) return res;
  res = await handleSuggestedPromptsRoute_6srbz(url, request, db); if (res) return res;
  res = await handleAuthPageRouteRoute_kd7du(url, request, db); if (res) return res;
  res = await handleCommunitiesFilterRoute_e6t80(url, request, db); if (res) return res;
  res = await handleCommunitiesGridRoute_evxz4(url, request, db); if (res) return res;
  res = await handleCommunitiesHeaderRoute_z0gd8(url, request, db); if (res) return res;
  res = await handleCommunitiesPageRoute_lsbt3(url, request, db); if (res) return res;
  res = await handleCreateCommunityModalRoute_tks0c(url, request, db); if (res) return res;
  res = await handleAISuggestionsRoute_sf8we(url, request, db); if (res) return res;
  res = await handleDashboardPageRoute_n2219(url, request, db); if (res) return res;
  res = await handleQuickActionsRoute_16szu(url, request, db); if (res) return res;
  res = await handleRecentActivityRoute_js47j(url, request, db); if (res) return res;
  res = await handleStatsGridRoute_sodgb(url, request, db); if (res) return res;
  res = await handleUpcomingScheduleRoute_fcra7(url, request, db); if (res) return res;
  res = await handleWelcomeHeaderRoute_7sa60(url, request, db); if (res) return res;
  res = await handleFeedPageRoute_ej59j(url, request, db); if (res) return res;
  res = await handleLandingPageRoute_inmd3(url, request, db); if (res) return res;
  res = await handleLeaderboardPageRoute_ldh0n(url, request, db); if (res) return res;
  res = await handlePodiumRoute_a1oqj(url, request, db); if (res) return res;
  res = await handleRankListRoute_fyis4(url, request, db); if (res) return res;
  res = await handleTrophyRoomRoute_9qmx8(url, request, db); if (res) return res;
  res = await handleChatAreaRoute_9396g(url, request, db); if (res) return res;
  res = await handleMessagesPageRoute_r73b4(url, request, db); if (res) return res;
  res = await handleMessagesSidebarRoute_lxj3a(url, request, db); if (res) return res;
  res = await handleNewChatModalRoute_cbjaj(url, request, db); if (res) return res;
  res = await handleCreateFolderModalRoute_hko04(url, request, db); if (res) return res;
  res = await handleCreateNoteModalRoute_9mx5e(url, request, db); if (res) return res;
  res = await handledataRoute_og8o6(url, request, db); if (res) return res;
  res = await handlefileExtractorRoute_jor63(url, request, db); if (res) return res;
  res = await handleFlashcardsStudyModalRoute_chrxq(url, request, db); if (res) return res;
  res = await handleFolderBreadcrumbsRoute_8sc96(url, request, db); if (res) return res;
  res = await handleFolderGridRoute_ks8rb(url, request, db); if (res) return res;
  res = await handleNotesFilterRoute_rd7y0(url, request, db); if (res) return res;
  res = await handleNotesHeaderRoute_g3vpg(url, request, db); if (res) return res;
  res = await handleNotesListRoute_h2cd5(url, request, db); if (res) return res;
  res = await handleNotesPageRoute_vvmna(url, request, db); if (res) return res;
  res = await handletypesRoute_mdrc7(url, request, db); if (res) return res;
  res = await handleChatPaneRoute_s2bsd(url, request, db); if (res) return res;
  res = await handleFlashcardsTabRoute_6sw61(url, request, db); if (res) return res;
  res = await handleindexRoute_zyssn(url, request, db); if (res) return res;
  res = await handleMermaidViewerRoute_kn4bp(url, request, db); if (res) return res;
  res = await handleSlideCarouselRoute_qwis2(url, request, db); if (res) return res;
  res = await handleindexRoute_vshhh(url, request, db); if (res) return res;
  res = await handleNoteWorkspaceModalRoute_gqjyl(url, request, db); if (res) return res;
  res = await handleSourcesPaneRoute_ed19r(url, request, db); if (res) return res;
  res = await handleStudioPaneRoute_ornb9(url, request, db); if (res) return res;
  res = await handlestudioUtilsRoute_kdabb(url, request, db); if (res) return res;
  res = await handleAIInsightsRoute_jmv9l(url, request, db); if (res) return res;
  res = await handleAIOptimizerModalRoute_tnd3y(url, request, db); if (res) return res;
  res = await handleCustomDatePickerRoute_fn148(url, request, db); if (res) return res;
  res = await handleLongTermGoalsRoute_mgy4h(url, request, db); if (res) return res;
  res = await handlePlannerActionModalRoute_jpm7r(url, request, db); if (res) return res;
  res = await handlePlannerConfirmModalRoute_197vi(url, request, db); if (res) return res;
  res = await handlePlannerHeaderRoute_830sj(url, request, db); if (res) return res;
  res = await handlePlannerPageRoute_22vrw(url, request, db); if (res) return res;
  res = await handleTodayScheduleRoute_fiaoj(url, request, db); if (res) return res;
  res = await handleWeeklyGoalsRoute_mnpgw(url, request, db); if (res) return res;
  res = await handleProfilePageRoute_ksh3j(url, request, db); if (res) return res;
  res = await handleCollaboratorsListRoute_7nidb(url, request, db); if (res) return res;
  res = await handlePaperSearchRoute_itfru(url, request, db); if (res) return res;
  res = await handleResearchHeaderRoute_umo0h(url, request, db); if (res) return res;
  res = await handleResearchPageRoute_l31mv(url, request, db); if (res) return res;
  res = await handleResearchPapersListRoute_t96re(url, request, db); if (res) return res;
  res = await handleResearchStatsRoute_t8j9f(url, request, db); if (res) return res;
  res = await handleAccessibilitySettingsPageRoute_g52kg(url, request, db); if (res) return res;
  res = await handleApiKeysPageRoute_hrllo(url, request, db); if (res) return res;
  res = await handleAppearanceSettingsPageRoute_n2pk7(url, request, db); if (res) return res;
  res = await handleDataManagementPageRoute_kn4lw(url, request, db); if (res) return res;
  res = await handleDataStorageHubPageRoute_gnas9(url, request, db); if (res) return res;
  res = await handleEmailSettingsPageRoute_a78dj(url, request, db); if (res) return res;
  res = await handleLanguageSettingsPageRoute_rnok0(url, request, db); if (res) return res;
  res = await handleMyCommentsPageRoute_y9v5h(url, request, db); if (res) return res;
  res = await handleMyLikesPageRoute_yq1jr(url, request, db); if (res) return res;
  res = await handleMyPostsPageRoute_zu33j(url, request, db); if (res) return res;
  res = await handleMySharesPageRoute_ahwdu(url, request, db); if (res) return res;
  res = await handleNotificationsSettingsPageRoute_35xu2(url, request, db); if (res) return res;
  res = await handlePasswordSettingsPageRoute_1on0p(url, request, db); if (res) return res;
  res = await handlePreferencesHubPageRoute_5f7xe(url, request, db); if (res) return res;
  res = await handlePrivacySettingsPageRoute_c1orf(url, request, db); if (res) return res;
  res = await handleProfileSettingsPageRoute_xr7rf(url, request, db); if (res) return res;
  res = await handleStorageUsagePageRoute_f3c3y(url, request, db); if (res) return res;
  res = await handleSettingsPageRoute_waysn(url, request, db); if (res) return res;

  return null;
};
